### ISSUE TITLE
function for calculating the score

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#3]
Again thanks for all your answer,

I want to apply and use some of your idea in my research,
Actually, I don't want the topic assignment part, rather the way you calculate the score for each word,
May I ask you to help me with your code, Do I need the computeKeywordScore? Or there are other dependencies I should consider?

Thank you so much for your time :)

**Comment by JohnTailor** [comment]
ComputeKeywordScore should work, but you can also check the formula in the paper. If you feel like you need some more help, it's possible to give much of direct support, but I can only recommend you to come to study at my university (University of Liechtenstein) and you can read the paper easily afterwards :-) .

**Comment by un-lock-me** [comment]
Thank you so much for explanations, Actually, I have started my Ph.D., at the US and so its not easy for me to come there to study the paper, if I had this option it would be great, but sadly I can not
thank you any way :)

actually, I used your code with any input it raises this error:
`numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 0`


`import numpy as np
import scipy

def computeKeywordScore(self, nwt, human=False):
    nw = np.sum(nwt, axis=1)  # number of times word occurs overall
    entropy_p_t_w = np.apply_along_axis(scipy.stats.entropy, 1,
                                        nwt + 1e-30)  # entropy of topic-word distr, small constant if word has 0 occurrences in all topics
    maxEntropy = np.log2(
        np.clip(nw, 2, self.nTopics))  # For concentration normalization: min (log #topics, log #times word occurs)
    concentration = (maxEntropy / (1 + entropy_p_t_w)) ** (1.5)
    if human:
        new_f_w_t = nwt * (
        concentration.reshape(concentration.shape[0], 1))  # human readable: stronger focus on frequncy
    else:
        new_f_w_t = np.log2(1 + nwt + self.beta) * (
        concentration.reshape(concentration.shape[0], 1))  # for inference/extracting keywords
    normconst = 1e-30 + np.sum(new_f_w_t, axis=0)  # sum across words for a topic # sum_z p(w|d,z)*p(z|d)
    for t in range(normconst.shape[0]): new_f_w_t[:, t] /= normconst[t]
    return new_f_w_t

nwt = np.zeros((2, 3), dtype=np.float32)
computeKeywordScore(nwt, False)`
