### ISSUE TITLE
evaluation part

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#4]
hi john,

would you please let me know the code for your evaluation part?
have you tried to visualize your data?
may I ask you to let me know with which implementation of LDA did you compare your result? if you have the link I appreciate it share it with me.

Thanks for your time :)

**Comment by JohnTailor** [comment]
Hi Saria, the code should already contain an output of the top words for each topic. That's fairly standard. For lda there are lots of libraries, gensim did not give me good results, so if I recall correctly I went for liblda.

Best
JOhannes

**Comment by un-lock-me** [comment]
Thanks for replying back, I meant by evaluation part the table you provided in the paper which compares "PMI" and "Distinct Topics score".

Thanks :)

**Comment by un-lock-me** [comment]
Sorry I guess I did not get you correctly, so you mean for finding PMI you reported in the paper I need to calculate the median of the whole numbers in each topic and then the mean of PMI of each calculated topics?
Would you please let me know is it the same thing you did in the paper?
Actually I got good result and I only need to evaluate the model so I appreciate it if you let me know about this.

Thanks:)
