### ISSUE TITLE
output does not make sense

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#5]
hello John

I have run your code on my dataset, its a large dataset about 500k txt documents
and the result does not make sense as most words got 0 percent and only 4 topic has been output.
would you please justify this?

thanks

```

0:    cvasoci 0.00000, mcireview 0.00000, panhypopituitarismreview 0.00000, calltrig 0.00000, orderslength 0.00000, showmiss 0.00000, gaitpt 0.00000, notepsychotherapi 0.00000, ucohl 0.00000, pulmonarydismiss 0.00000, wellnl 0.00000, utiresult 0.00000, welldc 0.00000, mammogramneg 0.00000, boquet 0.00000, 
1:    cvasoci 0.00000, mcireview 0.00000, panhypopituitarismreview 0.00000, calltrig 0.00000, orderslength 0.00000, showmiss 0.00000, gaitpt 0.00000, notepsychotherapi 0.00000, ucohl 0.00000, pulmonarydismiss 0.00000, wellnl 0.00000, utiresult 0.00000, welldc 0.00000, mammogramneg 0.00000, boquet 0.00000, 
2:    prescript 0.100, mouth 0.098, tablet 0.095, skin 0.088, clear 0.053, site 0.051, joint 0.050, lesion 0.046, neg 0.044, mild 0.043, deni 0.042, sleep 0.041, procedur 0.040, bowel 0.040, think 0.039, 
3:    baalmann 0.896, damian 0.669, cuffautomat 0.648, rachelen 0.442, balkcom 0.431, schwarz 0.368, klusmann 0.296, deceas 0.253, calv 0.250, rightarm 0.235, scholz 0.229, sztajnkrycer 0.211, sadosti 0.201, bernic 0.188, negativegu 0.162, 
4:    patient 0.207, time 0.155, mg 0.151, tablet 0.143, daili 0.092, mouth 0.091, pain 0.085, medic 0.068, dai 0.067, instruct 0.064, left 0.060, right 0.058, indic 0.058, dr 0.056, need 0.055, 
```

I have not changed your code except the way read the dataset:

    import re
    documents = glob.glob("/infodev1/phi-data/sohn/biobank/saria/biobank_65up_CI_dx_CN_cp/*.txt")
    docs = []
    for fi in documents:
        with open(fi, 'r') as myfile:
            d = myfile.read().replace('\n', '')
            d = re.sub(r"/[A-Za-z0-9_-]+ ", " ",
                       d)  # The/at Fulton/np-tl County/nn-tl Grand/jj-tl Jury/nn-tl said/vbd Friday/nr an/at investigation/nn") #.replace("/at","").replace("/nn-tl","").replace("/nn-hp","").replace("/np-hl","").replace("/nn","").replace("/vbd","").replace("/in","").replace("/jj","").replace("/hvz","").replace("/cs","").replace("/nps","").replace("/nr","").replace("/np-tl","").replace("/md","").replace("/np","").replace("/cd-hl","").replace("/vbn","").replace("/np-tl","").replace("/dti","").replace("--/--","")
            docs.append(d)
    return docs

**Comment by un-lock-me** [comment]
It seems that your code is dependent on the dataset. when I apply another biomedical data which is not that much large it does good. but when I apply that on a very large dataset of biomedical it did not well, I had a look on the paper but I did not see that it mentions that it dependent on the dataset.

Would you please clarify or confirm this?

Thanks, :)

**Comment by JohnTailor** [comment]
Hi Saria,

the TKM model as any other topic model like LDA has a few (hyper)parameters, namely alpha and beta (and gamma). These do have an influence. Also the results depend strongly on the dataset for any topic model. If you see (too few) topics, you might try a low alpha, e.g. 1, and maybe also a low gamma, e.g. 0.5.

Best
Johannes

**Comment by un-lock-me** [comment]
Actually I did resolve it by changing the parameters and also doing more preprocessing. 
Now the result makes sense.

Thanks :)
