### ISSUE TITLE
PMI evaluation

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#6]
I need to evaluate your approach on my data set 
Do you mean for finding PMI you reported in the paper I need to calculate the median of the whole numbers in each topic and then the mean of PMI of each calculated topics?
Would you please let me know is it the same thing you did in the paper?
Actually I got good result and I only need to evaluate the model so I appreciate it if you let me know about this.

Thanks:)

**Comment by JohnTailor** [comment]
For PMI you need an external corpus, eg Wikipedia. The idea is that the top words in a topic shoul also often co-occur (in the same article/document) in the external corpus.

**Comment by un-lock-me** [comment]
Oh sorry, my mind is too busy I have copy pasted the previous question!!
My question was about distinct topic measurement in which you have used sym kl divergence.
I could not see the implementation in the code, I was wondering do you have that by any chance?

**Comment by JohnTailor** [comment]
This is done in def getUniqueTopics(p_w_t,thres)  in file algtools.py

**Comment by un-lock-me** [comment]
Do you mind let me know how can I get it run in my case? what is this input stands for p_w_t?
Thanks :)

**Comment by JohnTailor** [comment]
p_w_t stands for probalibity of a word gjven a topic p(w|t) . that's what you get when you run the topic model. the parameter thres for def getuniquetopics is a threshold saying how different a topic must be from all others to be unique, it is between 0,1; i dont recall what i used in the paper - its written there, sth like 0.3 or so
