### ISSUE TITLE
How did you track the context

### ISSUE THREAD

**Issue by un-lock-me** [JohnTailor/tkm#7]
Hi :),

I have a question regarding the way you create the corpus, as stated in the paper this algorithm considers the context while assigning topic to words. I mean looking at a window before and after targeted word to assign the topic to words.

I think I may misunderstood  but how did you track the context of the words?
I looked at the methods for creating corpus in AlgTools, it seems the corpus  has been created regardless of their position in the documents. 
So, how you were able to see which words are around the targeted word?
Sorry for many question I need to know your approach for applying this part.

many Thanks :)

**Comment by un-lock-me** [comment]
I appreciate it if you let me know about this :)

**Comment by JohnTailor** [comment]
Context windows are not stored, they are computed on the fly, used and forgotten, see topicassign.pyx:
for ind in xrange(max(istart,doff-winwid),min(iend,doff+winwid+1)):

If you have a sentence: Hello World, I feel great and winwid=3 that would consider contexts like:
Hello World, I 
World, I feel 
I feel great
....

Best
Jo.

**Comment by un-lock-me** [comment]
Thanks for letting me know, I will check that script then ask you question,

Thanks :)
